services:
  gpx-web:
    environment:
      ROUTER_MODE: valhalla
      VALHALLA_URL: http://valhalla:8002
    depends_on:
      - valhalla

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      use_tiles_ignore_pbf: "False"
    networks:
      - media-net
    volumes:
      - ${VALHALLA_DATA_PATH}:/custom_files

networks:
  media-net:
    external: true
